teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Forward/Back
      x: 1
    scale_linear:
      x: 0.7

    axis_angular:  # Left/Right
      yaw: 0
    scale_angular:
      yaw: 0.4

    enable_button: 0  # Trigger

teleop_acker_joy_node:
  ros__parameters:
    axis.linear: 1
    scale.linear: .45
    #scale_turbo.linear: 0.7

    # this is for steering angle velocity.
    # a big number makes it more authorative about getting to setpoint
    # The scale is "about the angle error in rad" until stop
    axis.steering_angle_velocity: 1
    scale.steering_angle_velocity: 0.0
    #offset.steering_angle_velocity: 0.5
    #scale_turbo.steering_angle_velocity: 1.0

    # This is the steering angle in rad (about 0.015 rad in a degree)
    axis.steering_angle: 0
    scale.steering_angle: -0.4
    #scale_turbo.steering_angle: -0.7

    # Optional: have a separate "fine" axis
    # in this case, the coarse axis is considered separate.
    axis.steering_angle_fine: 3
    scale.steering_angle_fine: -0.4 # 1.4
    #scale_turbo.steering_angle_fine: -0.1

    enable_button: 0
    enable_turbo_button: -1

    failsafe_delay_ms: 100